version: 2
sources:
- name: testdb_1
  quoting:
    database: true
    schema: false
    identifier: false
  tables:
  - name: _airbyte_raw_products
  - name: _airbyte_raw_purchases
  - name: _airbyte_raw_users
